env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  -
    main: cmd/assumer/main.go
    binary: assumer
    goos:
      - linux
      - darwin
    goarch:
      - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
    - 'masahide/assumer:{{ .Tag }}'
    - 'masahide/assumer:v{{ .Major }}.{{ .Minor }}'
    - 'masahide/assumer:latest'
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  -
    github:
      owner: masahide
      name: assumer
    folder: Formula
    homepage:  https://github.com/masahide/assumer
    description: AWS assume role credential wrapper
    test: |
      system "#{bin}/assumer -v"

nfpms:
  -
    name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/masahide/assumer
    description: AWS assume role credential wrapper
    maintainer: "YAMASAKI Masahide <masahide.y@gmail.com>"
    license: MIT
    vendor: Assumer
    formats:
      - deb
      - rpm
# snapcraft:
#   name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#   summary: AWS assume role credential wrapper
#   description: AWS assume role credential wrapper
#   grade: stable
#   confinement: classic
