# This file was generated by GoReleaser. DO NOT EDIT.
class Assumer < Formula
  desc "AWS assume role credential wrapper"
  homepage "https://github.com/masahide/assumer"
  version "0.1.7"

  if OS.mac?
    url "https://github.com/masahide/assumer/releases/download/v0.1.7/assumer_Darwin_x86_64.tar.gz"
    sha256 "bcf024fb62e0bb096390a0c7811d6fb585163d7be226e39394c6a9b58fb248ca"
  elsif OS.linux?
    url "https://github.com/masahide/assumer/releases/download/v0.1.7/assumer_Linux_x86_64.tar.gz"
    sha256 "a9f3d2df2751aca72c6c7df087968c1937c742813c8e1a7857966c4857930061"
  end

  def install
    bin.install "assumer"
  end

  test do
    system "#{bin}/assumer -v"
  end
end
